### ISSUE TITLE
[Seg] smooth AxonSeg contour

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axon_segmentation#16]
![image](https://cloud.githubusercontent.com/assets/7785316/10806000/8d958414-7da8-11e5-91c4-fb2763f50c1f.png)

Something like as_smoothcontour

**Comment by alzaia** [comment]
Done for now (new function as_make_convex()). 
Added push button in the GUI (remove concavity) --> Select axons on screen to make them convex.
![screen shot 2015-11-10 at 3 34 28 pm](https://cloud.githubusercontent.com/assets/14980394/11075026/030e73be-87c1-11e5-84ad-508ab1284a50.png)
