### ISSUE TITLE
[NEW] Denoising

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axon_segmentation#2]
Add denoising in Step0 (or smoothing if too slow).

test on: /Volumes/data_shared/microscopy/issues/i_20150623_rats_PANO_SEM/2%PFA2%Gluta_short_rince_CaCl2_PANO_SEM/20150823_PanoramaSEM/Section 4.png

**Comment by alzaia** [comment]
See function as_gaussian_smoothing (called in Step0 of SegmentationGUI + in as_segmentation_full_image() for full image)
