### ISSUE TITLE
to change for V2

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/axon_segmentation#23]
- Adjust default parameters using pixelSize. Should work directly on most images.
- hide level set --> too complex currently
- remove "add" in DA
- Display border that is going to be removed --> border should be a function of pixelSize
- Display Red/green from step 2 
- let user click on ROC curve
- remove circularity
- Clean outputs of myelinSeg button + add colorbar with min max

Tanguy

**Comment by SaraDupont** [comment]
Clean codes

**Comment by alzaia** [comment]
Done!
