### ISSUE TITLE
Find parameters for step 2

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axon_segmentation#26]
- create a testing folder: image of different modalities + segmentation's ground truth
- remove step 2 , apply axonvalidation with 'standard" parameters based on shapes. Should work correctly on all microscopy of the testing g folder
- apply DA
- step3: ask user to correct in some ROI
- apply DA

Alexandre project could be "finding standard parameters for all image modality"

**Comment by alzaia** [comment]
Tanguy, not sure what you mean by "standard parameters"? Do you mean specific values that work most of the time in these images?

**Comment by tanguyduval** [comment]
Yes exactly!

-----Original Message-----

**Comment by alcohe** [comment]
Hi guys, have we looked at any stats from previous segmentation results in terms of the different values we use as parameters (area, circularity, etc)? For example I was looking at the data from a previously segmented image (Axonlist) and looking at distributions of the gRatio, myelin thickness and axon diameter. It would be interesting to do a similar exercise with the parameters mentioned above, and include TP, FP and TN to see if this can help us limit the range of parameters

**Comment by alcohe** [comment]
For example, these are the parameters that More 2011 used to limit the axon candidates: 
![image](https://cloud.githubusercontent.com/assets/16826004/12499264/03dbdb9e-c077-11e5-93a7-8161a3d476cc.png)

**Comment by alzaia** [comment]
Foe the axon part, I have already done an analysis for every possible parameter (& also ratios between 2 parameters), thats how I chose the current sliders in step 2 of the GUI. I can show you these results (I did some histograms for each parameter, true vs false axons).

**Comment by tanguyduval** [comment]
Nice, if you  could put those histograms on github plz!
Also compare with the values proposed by Alex. 

-----Original Message-----
