### ISSUE TITLE
[ENHANCEMENT] circularity threshold should be dependent on axon diameter 

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axon_segmentation#4]
Large axons are too easily removed in circularity test.
Test on:
/Volumes/data_shared/microscopy/issues/i_20150623_rats_PANO_SEM/2%PFA2%Gluta_short_rince_CaCl2_PANO_SEM/20150823_PanoramaSEM/Section 4.png

Maybe create a new validation slider using MinorAxisLength and MajorAxisLength.

**Comment by alzaia** [comment]
Although its better now when using a discriminant analysis (we can keep more small axons), I think the best option is to do a different segmentation depending on the axon size. I can split my initial axon objects in 2 clusters (by optimizing the separation between the 2) & then perform all our next segmentation steps for both clusters (one at a time), including different discriminant analysis for each cluster. This is the optimal solution, but more complex (see screen captures below). So we end up having 2 segParameters mat files (one for each axon object domain) & at the end we combine these 2 segmentations to get our final segmentation. What do you think Tanguy?

![screen shot 2015-11-19 at 5 22 27 pm](https://cloud.githubusercontent.com/assets/14980394/11286531/75f5f18a-8ee3-11e5-8c9d-03e643c4e093.png)
![screen shot 2015-11-19 at 5 22 35 pm](https://cloud.githubusercontent.com/assets/14980394/11286551/8b009ac6-8ee3-11e5-953e-f131493b3890.png)

**Comment by tanguyduval** [comment]
I would recommend simplicity... Discriminant analysis should handle that. I close the issue
